import { composite, hsl } from "./colors.mjs";

export function addChatThemes({ palette, add, solid, overlay, derived }) {
  const base = solid("base");
  const panel = solid("panel");
  const text = solid("text");
  const faint = solid("faintText");
  const warm = solid("warm");
  const accent = solid("accent");
  const border = solid("border");
  const error = solid("error");
  // Presence/success is a deliberate port mapping, not a new canonical role.
  const status = solid("document");
  const selection = composite(derived("textSelection"), base);
  const panelSelection = composite(derived("textSelection"), panel);
  const selectedOutgoing = composite(derived("textSelection"), panelSelection);
  const hover = composite(overlay("hover"), panel);
  const separator = composite(overlay("separator"), panel);
  const accentHsl = hsl(accent);

  const discord = {
    "--background-base-low": base,
    "--background-base-lower": panel,
    "--background-base-lowest": base,
    "--background-surface-high": panel,
    "--background-surface-higher": panel,
    "--background-surface-highest": hover,
    "--app-frame-background": base,
    "--app-frame-border": overlay("separator"),
    "--chat-background": base,
    "--chat-background-default": base,
    "--custom-channel-members-bg": panel,
    "--background-primary": base,
    "--background-secondary": panel,
    "--background-secondary-alt": panel,
    "--background-tertiary": base,
    "--background-accent": panel,
    "--background-floating": panel,
    "--background-nested-floating": panel,
    "--bg-base-primary": base,
    "--bg-base-secondary": panel,
    "--bg-base-tertiary": base,
    "--bg-surface-raised": panel,
    "--bg-surface-overlay": panel,
    "--modal-background": panel,
    "--modal-footer-background": panel,
    "--card-background-default": panel,
    "--card-primary-bg": panel,
    "--background-code": base,
    "--text-default": text,
    "--text-primary": text,
    "--text-normal": text,
    "--text-strong": warm,
    "--text-secondary": faint,
    "--text-tertiary": faint,
    "--text-muted": faint,
    "--text-subtle": faint,
    "--chat-text-muted": faint,
    "--header-primary": warm,
    "--header-secondary": text,
    "--header-muted": faint,
    "--text-link": warm,
    "--text-brand": accent,
    "--channels-default": faint,
    "--channel-icon": faint,
    "--icon-primary": text,
    "--icon-secondary": faint,
    "--icon-tertiary": faint,
    "--interactive-normal": text,
    "--interactive-hover": warm,
    "--interactive-active": warm,
    "--interactive-muted": faint,
    "--interactive-icon-default": text,
    "--interactive-icon-hover": warm,
    "--interactive-icon-active": warm,
    "--interactive-text-hover": warm,
    "--interactive-text-active": warm,
    "--background-modifier-hover": overlay("hover"),
    "--background-modifier-active": overlay("hover"),
    "--background-modifier-selected": derived("textSelection"),
    "--background-modifier-accent": overlay("separator"),
    "--background-mod-muted": overlay("hover"),
    "--background-mod-subtle": overlay("hover"),
    "--background-mod-normal": overlay("hover"),
    "--background-mod-strong": derived("textSelection"),
    "--interactive-background-hover": overlay("hover"),
    "--interactive-background-active": overlay("hover"),
    "--interactive-background-selected": derived("textSelection"),
    "--background-message-hover": overlay("hover"),
    "--message-background-hover": overlay("hover"),
    "--background-mentioned": derived("textSelection"),
    "--background-mentioned-hover": panelSelection,
    "--message-mentioned-background-default": derived("textSelection"),
    "--message-mentioned-background-hover": panelSelection,
    "--background-message-highlight": derived("textSelection"),
    "--background-message-highlight-hover": panelSelection,
    "--message-highlight-background-default": derived("textSelection"),
    "--message-highlight-background-hover": panelSelection,
    "--mention-background": derived("textSelection"),
    "--mention-foreground": warm,
    "--message-reacted-background-default": derived("textSelection"),
    "--message-reacted-text-default": warm,
    "--brand-500": accent,
    "--brand-500-hsl": `${accentHsl.h} ${accentHsl.s}% ${accentHsl.l}%`,
    "--brand-experiment": accent,
    "--brand-experiment-500": accent,
    "--bg-brand": accent,
    "--background-brand": accent,
    "--control-brand-foreground": accent,
    "--control-brand-foreground-new": accent,
    "--control-primary-background-default": accent,
    "--control-primary-background-hover": text,
    "--control-primary-background-active": warm,
    "--button-filled-brand-background": accent,
    "--button-filled-brand-background-hover": text,
    "--button-filled-brand-background-active": warm,
    "--button-filled-brand-text": base,
    "--control-secondary-background-default": panel,
    "--control-secondary-background-hover": hover,
    "--control-secondary-background-active": panelSelection,
    "--control-secondary-text-default": text,
    "--button-secondary-background": panel,
    "--button-secondary-background-hover": hover,
    "--button-secondary-background-active": panelSelection,
    "--button-secondary-text": text,
    "--button-danger-background": error,
    "--button-danger-background-hover": error,
    "--button-danger-background-active": error,
    "--button-danger-text": base,
    "--input-background-default": base,
    "--input-background": base,
    "--channeltextarea-background": panel,
    "--deprecated-text-input-bg": base,
    "--input-text-default": text,
    "--input-placeholder-text-default": faint,
    "--channel-text-area-placeholder": faint,
    "--input-border-default": border,
    "--input-border": border,
    "--deprecated-text-input-border": border,
    "--border-faint": overlay("separator"),
    "--border-subtle": overlay("separator"),
    "--border-muted": border,
    "--border-normal": border,
    "--border-strong": border,
    "--divider-subtle": overlay("separator"),
    "--focus-primary": accent,
    "--scrollbar-auto-thumb": border,
    "--scrollbar-thin-thumb": border,
    "--scrollbar-auto-scrollbar-color-thumb": border,
    "--scrollbar-auto-track": base,
    "--scrollbar-thin-track": base,
    "--scrollbar-auto-scrollbar-color-track": base,
    "--status-online": status,
    "--status-positive": status,
    "--status-speaking": status,
    "--status-idle": solid("warning"),
    "--status-dnd": error,
    "--status-danger": error,
    "--status-offline": faint,
    "--text-positive": status,
    "--text-feedback-positive": status,
    "--text-warning": solid("warning"),
    "--text-feedback-warning": solid("warning"),
    "--text-danger": warm,
    "--text-feedback-critical": warm
  };
  for (const state of ["default", "hover", "active"]) {
    discord[`--control-primary-text-${state}`] = base;
    discord[`--control-primary-icon-${state}`] = base;
  }
  const darkThemes = [".theme-dark", ".theme-darker", ".theme-midnight"];
  const discordSelectors = darkThemes.flatMap(selector => [
    selector, `.visual-refresh${selector}`, `.visual-refresh ${selector}`
  ]).join(",\n");
  add("targets/discord/DeepSeaFoam.theme.css", `/**
 * @name DeepSeaFoam
 * @author Zanark
 * @description Unofficial DeepSeaFoam theme for existing BetterDiscord or Vencord desktop clients.
 * @version ${palette.version}
 * @source https://github.com/Zanark/DeepSeaFoam
 * @website https://zanark.github.io/DeepSeaFoam/
 */

/* Generated from palette/deepseafoam.json.
 * Not a native Discord import or a marketplace-approved theme.
 * Client modifications may violate Discord's terms and are not account-risk-free.
 * Semantic colors only; no external resources or media transformations.
 */

${discordSelectors} {
${Object.entries(discord).map(([name, value]) => `  ${name}: ${value} !important;`).join("\n")}
}

${darkThemes.map(selector => `${selector} ::selection`).join(",\n")} {
  color: ${warm};
  background-color: ${selection};
}
`);

  // Explicit core surfaces avoid inheriting Telegram's hard-coded light defaults.
  const telegram = {
    windowBg: base,
    windowFg: text,
    windowBgOver: hover,
    windowBgRipple: panelSelection,
    windowFgOver: warm,
    windowSubTextFg: faint,
    windowSubTextFgOver: text,
    windowBoldFg: warm,
    windowBoldFgOver: warm,
    windowBgActive: accent,
    windowFgActive: base,
    windowActiveTextFg: accent,
    windowShadowFg: overlay("shadowStrong"),
    windowShadowFgFallback: separator,
    shadowFg: overlay("separator"),
    slideFadeOutBg: overlay("backdrop"),
    slideFadeOutShadowFg: overlay("shadowStrong"),
    activeButtonBg: accent,
    activeButtonBgOver: text,
    activeButtonBgRipple: warm,
    activeButtonFg: base,
    activeButtonFgOver: base,
    activeButtonSecondaryFg: base,
    activeButtonSecondaryFgOver: base,
    activeLineFg: accent,
    activeLineFgError: error,
    lightButtonBg: panel,
    lightButtonBgOver: hover,
    lightButtonBgRipple: panelSelection,
    lightButtonFg: accent,
    lightButtonFgOver: warm,
    attentionButtonFg: error,
    attentionButtonFgOver: warm,
    attentionButtonBgOver: composite(derived("errorBackground"), panel),
    attentionButtonBgRipple: composite(derived("errorBackgroundHover"), panel),
    menuBg: panel,
    menuBgOver: hover,
    menuBgRipple: panelSelection,
    menuIconFg: faint,
    menuIconFgOver: warm,
    menuSubmenuArrowFg: text,
    menuFgDisabled: faint,
    menuSeparatorFg: separator,
    scrollBarBg: border,
    scrollBarBgOver: accent,
    scrollBg: overlay("hover"),
    scrollBgOver: overlay("separator"),
    smallCloseIconFg: faint,
    smallCloseIconFgOver: warm,
    radialFg: warm,
    radialBg: overlay("shadowSoft"),
    placeholderFg: faint,
    placeholderFgActive: faint,
    inputBorderFg: border,
    filterInputBorderFg: accent,
    filterInputActiveBg: base,
    filterInputInactiveBg: base,
    checkboxFg: border,
    botKbBg: panel,
    botKbDownBg: panelSelection,
    botKbColor: text,
    sliderBgInactive: border,
    sliderBgActive: accent,
    tooltipBg: panel,
    tooltipFg: text,
    tooltipBorderFg: border,
    titleShadow: overlay("separator"),
    titleBg: panel,
    titleBgActive: panel,
    titleFg: faint,
    titleFgActive: warm,
    titleButtonBg: panel,
    titleButtonFg: faint,
    titleButtonBgOver: hover,
    titleButtonFgOver: warm,
    titleButtonCloseBgOver: error,
    titleButtonCloseFgOver: base,
    trayCounterBg: error,
    trayCounterBgMute: faint,
    trayCounterFg: base,
    layerBg: overlay("backdrop"),
    cancelIconFg: faint,
    cancelIconFgOver: warm,
    boxBg: panel,
    boxTextFg: text,
    boxTextFgGood: status,
    boxTextFgError: error,
    boxTitleFg: warm,
    boxSearchBg: base,
    boxTitleAdditionalFg: faint,
    boxDividerBg: base,
    boxDividerFg: separator,
    contactsBg: panel,
    contactsBgOver: hover,
    contactsNameFg: warm,
    contactsStatusFg: faint,
    contactsStatusFgOver: text,
    contactsStatusFgOnline: status,
    dialogsBg: base,
    dialogsNameFg: warm,
    dialogsChatIconFg: faint,
    dialogsDateFg: faint,
    dialogsTextFg: faint,
    dialogsTextFgService: accent,
    dialogsDraftFg: error,
    dialogsVerifiedIconBg: accent,
    dialogsVerifiedIconFg: base,
    dialogsSendingIconFg: faint,
    dialogsSentIconFg: status,
    dialogsUnreadBg: accent,
    dialogsUnreadBgMuted: faint,
    dialogsUnreadFg: base,
    dialogsOnlineBadgeFg: status,
    dialogsBgOver: hover,
    dialogsNameFgOver: warm,
    dialogsChatIconFgOver: warm,
    dialogsDateFgOver: text,
    dialogsTextFgOver: text,
    dialogsTextFgServiceOver: warm,
    dialogsDraftFgOver: warm,
    dialogsSendingIconFgOver: text,
    dialogsSentIconFgOver: status,
    dialogsBgActive: selection,
    dialogsNameFgActive: warm,
    dialogsChatIconFgActive: warm,
    dialogsDateFgActive: text,
    dialogsTextFgActive: text,
    dialogsTextFgServiceActive: warm,
    dialogsDraftFgActive: warm,
    dialogsVerifiedIconBgActive: accent,
    dialogsVerifiedIconFgActive: base,
    dialogsSendingIconFgActive: text,
    dialogsSentIconFgActive: status,
    dialogsUnreadBgActive: accent,
    dialogsUnreadBgMutedActive: faint,
    dialogsUnreadFgActive: base,
    dialogsOnlineBadgeFgActive: status,
    dialogsRippleBg: panelSelection,
    dialogsRippleBgActive: panelSelection,
    searchedBarBg: panel,
    searchedBarFg: text,
    searchedTextMatchBg: selection,
    searchedTextMatchFg: warm,
    searchedTextCurrentMatchBg: panelSelection,
    searchedTextCurrentMatchFg: warm,
    topBarBg: panel,
    emojiPanBg: panel,
    emojiPanCategories: panel,
    emojiPanHeaderFg: faint,
    emojiPanHeaderBg: panel,
    emojiIconFg: faint,
    emojiSubIconFgActive: accent,
    historyTextInFg: text,
    historyTextInFgSelected: warm,
    historyTextOutFg: text,
    historyTextOutFgSelected: warm,
    historyLinkInFg: accent,
    historyLinkInFgSelected: warm,
    historyLinkOutFg: warm,
    historyLinkOutFgSelected: warm,
    historyFileNameInFg: text,
    historyFileNameInFgSelected: warm,
    historyFileNameOutFg: text,
    historyFileNameOutFgSelected: warm,
    historyOutIconFg: status,
    historyOutIconFgSelected: status,
    historyIconFgInverted: warm,
    historySendingOutIconFg: text,
    historySendingInIconFg: faint,
    historySendingInvertedIconFg: warm,
    historyUnreadBarBg: panel,
    historyUnreadBarBorder: overlay("separator"),
    historyUnreadBarFg: accent,
    historyForwardChooseBg: overlay("backdrop"),
    historyForwardChooseFg: warm,
    historyScrollBarBg: border,
    historyScrollBarBgOver: accent,
    historyScrollBg: overlay("hover"),
    historyScrollBgOver: overlay("separator"),
    msgInBg: panel,
    msgInBgSelected: panelSelection,
    msgOutBg: panelSelection,
    msgOutBgSelected: selectedOutgoing,
    msgInServiceFg: accent,
    msgInServiceFgSelected: warm,
    msgOutServiceFg: warm,
    msgOutServiceFgSelected: warm,
    msgInShadow: overlay("shadowSoft"),
    msgInShadowSelected: overlay("shadowSoft"),
    msgOutShadow: overlay("shadowSoft"),
    msgOutShadowSelected: overlay("shadowSoft"),
    msgInDateFg: faint,
    msgInDateFgSelected: warm,
    msgOutDateFg: text,
    msgOutDateFgSelected: warm,
    // Active buttons use dark ink; service messages need an explicit warm override.
    msgServiceFg: warm,
    msgServiceBg: panel,
    msgServiceBgSelected: panelSelection,
    msgInReplyBarColor: accent,
    msgInReplyBarSelColor: accent,
    msgOutReplyBarColor: accent,
    msgOutReplyBarSelColor: accent,
    msgInMonoFg: warm,
    msgOutMonoFg: warm,
    msgInMonoFgSelected: warm,
    msgOutMonoFgSelected: warm,
    msgDateImgFg: warm,
    historyToDownBg: panel,
    historyToDownBgOver: hover,
    historyToDownBgRipple: panelSelection,
    historyToDownFg: text,
    historyToDownFgOver: warm,
    historyToDownShadow: overlay("shadowSoft"),
    historyComposeAreaBg: panel,
    historyComposeAreaFg: text,
    historyComposeAreaFgService: faint,
    historyComposeIconFg: faint,
    historyComposeIconFgOver: warm,
    historySendIconFg: accent,
    historySendIconFgOver: warm,
    historyPinnedBg: panel,
    historyReplyBg: panel,
    historyReplyIconFg: accent,
    historyReplyCancelFg: faint,
    historyReplyCancelFgOver: warm,
    historyComposeButtonBg: panel,
    historyComposeButtonBgOver: hover,
    historyComposeButtonBgRipple: panelSelection,
    mainMenuBg: panel,
    mainMenuCoverBg: base,
    mainMenuCloudFg: accent,
    mainMenuCloudBg: panel,
    notificationBg: panel,
    toastBg: panel,
    toastFg: warm,
    sideBarBg: panel,
    sideBarBgActive: base,
    sideBarBgRipple: panelSelection,
    sideBarTextFg: faint,
    sideBarTextFgActive: accent,
    sideBarIconFg: faint,
    sideBarIconFgActive: accent,
    sideBarBadgeBg: accent,
    sideBarBadgeBgActive: accent,
    sideBarBadgeBgMuted: faint,
    sideBarBadgeBgMutedActive: faint,
    sideBarBadgeFg: base
  };
  add("targets/telegram/DeepSeaFoam.tdesktop-theme",
    `// DeepSeaFoam ${palette.version}\n` +
    "// Generated from palette/deepseafoam.json. Native colors-only Telegram Desktop theme.\n" +
    "// No bundled wallpaper; unspecified keys use Telegram's compiled fallbacks.\n\n" +
    Object.entries(telegram).map(([name, value]) => `${name}: ${value};`).join("\n") + "\n");

  add("targets/slack/DeepSeaFoam.txt",
    ["panel", "accent", "document", "error"].map(role => solid(role)).join(",") + "\n");
}
